## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns=['EIN', 'NAME'], inplace=True)

In [4]:
# Determine the number of unique values in each column.
unique_values_count = application_df.nunique()
unique_values_count

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 500
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_gt_1 = classification_counts[classification_counts > 1]
classification_counts_gt_1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [12]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
class_cutoff_value = 100 
classifications_to_replace = classification_counts[classification_counts < class_cutoff_value].index.tolist()
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
#application_df['CLASSIFICATION'].value_counts()
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_encoded = pd.get_dummies(application_df)
application_df_encoded

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [16]:
# Split our preprocessed data into our features and target arrays
X = application_df_encoded.drop(columns=['ASK_AMT'])
y = application_df_encoded['ASK_AMT']
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [18]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

C:\Users\lukeb\anaconda3\envs\dev\Lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 80)                  │           4,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 30)                  │           2,430 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              31 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 6,461 (25.24 KB)

 Trainable params: 6,461 (25.24 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [21]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=100, verbose=1)

Epoch 1/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 943us/step - accuracy: 0.0000e+00 - loss: -157855152.0000
Epoch 2/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 849us/step - accuracy: 0.0000e+00 - loss: -3127596288.0000
Epoch 3/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 748us/step - accuracy: 0.0000e+00 - loss: -16017152000.0000
Epoch 4/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 806us/step - accuracy: 0.0000e+00 - loss: -41673351168.0000
Epoch 5/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 763us/step - accuracy: 0.0000e+00 - loss: -80091815936.0000
Epoch 6/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 799us/step - accuracy: 0.0000e+00 - loss: -125126983680.0000
Epoch 7/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 863us/step - accuracy: 0.0000e+00 - loss: -180176535552.0000
Epoch 8/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 751us/step - accuracy: 0.0000e+00 - loss: -224695500800.0000
Epoch 9/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 834us/step - accuracy: 0.0000e+00 - loss: -419525328896.0000
Epoch 10/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 744us/step - accuracy: 0.0000e+00 - loss: -466330091520.0000
Epoch 11/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 780us/step - accuracy: 0.0000e+00 - loss: -926929190912.0000
Epoch 12/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 809us/step - accuracy: 0.0000e+00 - loss: -641808924672.0000
Epoch 13/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 776us/step - accuracy: 0.0000e+00 - loss: -906962272256.0000
Epoch 14/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 796us/step - accuracy: 0.0000e+00 - loss: -1077798764544.0000
Epoch 15/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 833us/step - accuracy: 0.0000e+00 - loss: -1173790916608.0000
Epoch 16/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 800us/step - accuracy: 0.0000e+00 - loss: -2858678747136.0000
Epoch 17/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 764us/step - accuracy: 0.0000e+00 - loss: -1980525576192.0000
Epoch 18/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 813us/step - accuracy: 0.0000e+00 - loss: -2712365957120.0000
Epoch 19/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 701us/step - accuracy: 0.0000e+00 - loss: -2700751929344.0000
Epoch 20/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 760us/step - accuracy: 0.0000e+00 - loss: -3437066715136.0000
Epoch 21/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 744us/step - accuracy: 0.0000e+00 - loss: -3021062799360.0000
Epoch 22/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 764us/step - accuracy: 0.0000e+00 - loss: -3748065181696.0000
Epoch 23/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 763us/step - accuracy: 0.0000e+00 - loss: -4786931367936.0000
Epoch 24/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 774us/step - accuracy: 0.0000e+00 - loss: -9440383205376.0000
Epoch 25/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 710us/step - accuracy: 0.0000e+00 - loss: -5691724529664.0000
Epoch 26/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 746us/step - accuracy: 0.0000e+00 - loss: -7234613936128.0000
Epoch 27/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 741us/step - accuracy: 0.0000e+00 - loss: -6690055389184.0000
Epoch 28/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 745us/step - accuracy: 0.0000e+00 - loss: -6720768180224.0000
Epoch 29/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 818us/step - accuracy: 0.0000e+00 - loss: -9192472576000.0000
Epoch 30/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 783us/step - accuracy: 0.0000e+00 - loss: -11022445314048.0000
Epoch 31/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 832us/step - accuracy: 0.0000e+00 - loss: -12478220075008.0000
Epoch 32/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 807us/step - accuracy: 0.0000e+00 - loss: -12252002385920.0000
Epoch 33/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 780us/step - accuracy: 0.0000e+00 - loss: -15627904352256.0000
Epoch 34/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 849us/step - accuracy: 0.0000e+00 - loss: -12028332736512.0000
Epoch 35/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 754us/step - accuracy: 0.0000e+00 - loss: -11911253983232.0000
Epoch 36/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 790us/step - accuracy: 0.0000e+00 - loss: -15687203422208.0000
Epoch 37/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 834us/step - accuracy: 0.0000e+00 - loss: -13788429418496.0000
Epoch 38/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 784us/step - accuracy: 0.0000e+00 - loss: -20137163882496.0000
Epoch 39/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 840us/step - accuracy: 0.0000e+00 - loss: -23146277109760.0000
Epoch 40/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 823us/step - accuracy: 0.0000e+00 - loss: -16791037280256.0000
Epoch 41/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 820us/step - accuracy: 0.0000e+00 - loss: -19340852199424.0000
Epoch 42/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 844us/step - accuracy: 0.0000e+00 - loss: -16647517634560.0000
Epoch 43/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 798us/step - accuracy: 0.0000e+00 - loss: -31396017995776.0000
Epoch 44/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 815us/step - accuracy: 0.0000e+00 - loss: -18881624145920.0000
Epoch 45/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 901us/step - accuracy: 0.0000e+00 - loss: -23259032584192.0000
Epoch 46/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 792us/step - accuracy: 0.0000e+00 - loss: -28938854203392.0000
Epoch 47/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.0000e+00 - loss: -21136943349760.0000
Epoch 48/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 902us/step - accuracy: 0.0000e+00 - loss: -31812250238976.0000
Epoch 49/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 836us/step - accuracy: 0.0000e+00 - loss: -25251914186752.0000
Epoch 50/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 758us/step - accuracy: 0.0000e+00 - loss: -30354729598976.0000
Epoch 51/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 797us/step - accuracy: 0.0000e+00 - loss: -40580956553216.0000
Epoch 52/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 896us/step - accuracy: 0.0000e+00 - loss: -30521205719040.0000
Epoch 53/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 800us/step - accuracy: 0.0000e+00 - loss: -61732538023936.0000
Epoch 54/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0000e+00 - loss: -49214272831488.0000
Epoch 55/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0000e+00 - loss: -38190102609920.0000
Epoch 56/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 993us/step - accuracy: 0.0000e+00 - loss: -58994454429696.0000
Epoch 57/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 787us/step - accuracy: 0.0000e+00 - loss: -63566040268800.0000
Epoch 58/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 778us/step - accuracy: 0.0000e+00 - loss: -39567985999872.0000
Epoch 59/100

858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 769us/step - accuracy: 0.0000e+00 - loss: -53224602075136.0000
Epoch 60/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 752us/step - accuracy: 0.0000e+00 - loss: -49184954646528.0000
Epoch 61/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 748us/step - accuracy: 0.0000e+00 - loss: -55408798466048.0000
Epoch 62/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 803us/step - accuracy: 0.0000e+00 - loss: -72413081501696.0000
Epoch 63/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 818us/step - accuracy: 0.0000e+00 - loss: -73620411908096.0000
Epoch 64/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 749us/step - accuracy: 0.0000e+00 - loss: -96527561261056.0000
Epoch 65/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 745us/step - accuracy: 0.0000e+00 - loss: -95870137663488.0000
Epoch 66/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 759us/step - accuracy: 0.0000e+00 - loss: -91459055255552.0000
Epoch 67/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 904us/step - accuracy: 0.0000e+00 - loss: -130259420708864.0000
Epoch 68/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 751us/step - accuracy: 0.0000e+00 - loss: -79846109609984.0000
Epoch 69/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 835us/step - accuracy: 0.0000e+00 - loss: -101682880970752.0000
Epoch 70/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 774us/step - accuracy: 0.0000e+00 - loss: -93865193242624.0000
Epoch 71/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 855us/step - accuracy: 0.0000e+00 - loss: -80122086424576.0000
Epoch 72/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 803us/step - accuracy: 0.0000e+00 - loss: -75870848942080.0000
Epoch 73/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 741us/step - accuracy: 0.0000e+00 - loss: -137561586532352.0000
Epoch 74/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 833us/step - accuracy: 0.0000e+00 - loss: -130112754286592.0000
Epoch 75/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 748us/step - accuracy: 0.0000e+00 - loss: -98909221289984.0000
Epoch 76/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 797us/step - accuracy: 0.0000e+00 - loss: -131014236045312.0000
Epoch 77/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 796us/step - accuracy: 0.0000e+00 - loss: -160856960663552.0000
Epoch 78/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 874us/step - accuracy: 0.0000e+00 - loss: -118536735293440.0000
Epoch 79/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 782us/step - accuracy: 0.0000e+00 - loss: -132120483725312.0000
Epoch 80/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 879us/step - accuracy: 0.0000e+00 - loss: -124491497734144.0000
Epoch 81/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 721us/step - accuracy: 0.0000e+00 - loss: -176355249487872.0000
Epoch 82/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 780us/step - accuracy: 0.0000e+00 - loss: -115108277649408.0000
Epoch 83/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 847us/step - accuracy: 0.0000e+00 - loss: -134484024360960.0000
Epoch 84/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 743us/step - accuracy: 0.0000e+00 - loss: -111502266728448.0000
Epoch 85/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 798us/step - accuracy: 0.0000e+00 - loss: -133769163964416.0000
Epoch 86/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 784us/step - accuracy: 0.0000e+00 - loss: -125854956912640.0000
Epoch 87/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 719us/step - accuracy: 0.0000e+00 - loss: -145853280944128.0000
Epoch 88/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 701us/step - accuracy: 0.0000e+00 - loss: -175448742952960.0000
Epoch 89/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 801us/step - accuracy: 0.0000e+00 - loss: -151680343605248.0000
Epoch 90/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 826us/step - accuracy: 0.0000e+00 - loss: -214635806457856.0000
Epoch 91/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 755us/step - accuracy: 0.0000e+00 - loss: -232331524702208.0000
Epoch 92/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 812us/step - accuracy: 0.0000e+00 - loss: -144999840743424.0000
Epoch 93/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 816us/step - accuracy: 0.0000e+00 - loss: -258088594571264.0000
Epoch 94/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0000e+00 - loss: -285281425031168.0000
Epoch 95/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0000e+00 - loss: -367156386594816.0000
Epoch 96/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0000e+00 - loss: -168036636033024.0000
Epoch 97/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0000e+00 - loss: -300193450819584.0000
Epoch 98/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 913us/step - accuracy: 0.0000e+00 - loss: -246281930801152.0000
Epoch 99/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 897us/step - accuracy: 0.0000e+00 - loss: -198050270150656.0000
Epoch 100/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 877us/step - accuracy: 0.0000e+00 - loss: -215578333675520.0000

In [37]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/8575 - 0s - loss: 0.5578 - acc: 0.7263
Loss: 0.557812534073699, Accuracy: 0.7262973785400391

In [22]:
# Export our model to HDF5 file
nn.save("trained_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.